export const CHAPTERS = [
  {
    id: 1, title: "Giới thiệu", icon: "🏗️", color: "#b5722a",
    sections: [
      { id:"1-1", title:"Mô tả dự án", content:`## 1.1 Mô tả Dự án\n\nNăm 2009, một kênh đào dân cư được đề xuất tại **Khu phát triển Pimpama Riverside** và cuộc khảo sát địa kỹ thuật được thực hiện để đánh giá điều kiện địa kỹ thuật của khu vực.\n\nKết quả điều tra bao gồm:\n- Bản đồ khu vực với các đường đồng mức cao độ\n- Nhật ký hố khoan từ **BH1 đến BH10**\n- Báo cáo phòng thí nghiệm\n\nMục tiêu chính là xác định tính chất đất và ước tính các nguy cơ địa kỹ thuật.\n\n> 💡 Vấn đề địa kỹ thuật chính: **Sét rất mềm phân bố rộng** không phù hợp làm nền móng cho hầu hết các công trình.`, quiz:[{q:"Dự án kênh đào Pimpama được đề xuất năm nào?",options:["2005","2007","2009","2011"],ans:2,explain:"Năm 2009 tại Pimpama Riverside Development."},{q:"Vấn đề địa kỹ thuật chính là gì?",options:["Đá cứng","Sét rất mềm phân bố rộng","Cát chảy","Nước ngầm nông"],ans:1,explain:"Sét rất mềm phân bố rộng, không phù hợp làm nền móng."}]},
      { id:"1-2", title:"Dữ liệu thực địa", content:`## 1.2 Dữ liệu Thực địa\n\n### Bản đồ công trường\n\nKhu vực có cao độ từ **−0.97 m đến −2.4 m**. Mười hố khoan (BH1–BH10) bố trí để đánh giá điều kiện địa chất.\n\n### Thí nghiệm xuyên động (DCPT)\n\nThực hiện gần BH9. Số nhát búa $N_d$ thấp ở lớp trên cho thấy đất có **cường độ rất thấp**.\n\n| Độ sâu (cm) | $N_d$ | Nhận xét |\n|---|---|---|\n| 0–230 | 1–6 | Rất mềm |\n| 230–460 | 4–9 | Trung bình |\n| 460–690 | 6–21 | Cứng hơn |`, quiz:[{q:"DCPT đo thông số nào?",options:["Góc ma sát","Số nhát búa xuyên 10 cm","Hệ số thấm","Giới hạn chảy"],ans:1,explain:"$N_d$ = số nhát búa cần xuyên 10 cm vào đất."}]},
      { id:"1-3", title:"Dữ liệu phòng thí nghiệm", content:`## 1.3 Dữ liệu Phòng thí nghiệm\n\nBa loại đất được thí nghiệm:\n\n1. **Sét pha bùn phù sa** — lớp đất chính\n2. **Đất tàn tích** — lớp dưới\n3. **Cát từ hố thử Pit 1** — vật liệu đắp\n\n### Các thí nghiệm thực hiện\n- Phân tích thành phần hạt\n- Giới hạn Atterberg (LL, PL)\n- Mật độ và độ ẩm tự nhiên\n- Trọng lượng riêng hạt $G_s$`, quiz:[{q:"Có bao nhiêu loại đất được thí nghiệm?",options:["1","2","3","4"],ans:2,explain:"Ba loại: sét pha bùn phù sa, đất tàn tích và cát."}]}
    ]
  },
  {
    id: 2, title: "Sự hình thành và thăm dò đất", icon: "🌍", color: "#3d8b5e",
    sections: [
      { id:"2-1", title:"Phong hóa đá và hình thành đất", content:`## 2.1 Phong hóa đá và Hình thành đất\n\n### Phong hóa vật lý\n- Phá vỡ đá thành mảnh nhỏ do nhiệt độ, áp lực\n- **Không** thay đổi thành phần hóa học\n\n### Phong hóa hóa học\n- Thay đổi thành phần khoáng vật\n- Tạo ra khoáng vật sét mới\n- Quan trọng hơn ở **vùng nhiệt đới ẩm**\n\n> 💡 Quá trình phong hóa quyết định tính chất cơ bản của đất.`, quiz:[{q:"Loại phong hóa nào thay đổi thành phần hóa học đá?",options:["Vật lý","Hóa học","Sinh học","Cơ học"],ans:1,explain:"Phong hóa hóa học thay đổi khoáng vật, tạo ra sét mới."}]},
      { id:"2-2", title:"Đất tàn tích và đất vận chuyển", content:`## 2.2 Đất tàn tích và Đất vận chuyển\n\n### Đất tàn tích (Residual Soil)\n- Hình thành **tại chỗ** từ đá gốc bên dưới\n- Tính chất thay đổi theo độ sâu\n\n### Đất vận chuyển (Transported Soil)\n\n| Loại | Tác nhân | Ví dụ |\n|------|----------|-------|\n| Phù sa | Nước | Đồng bằng sông Cửu Long |\n| Eolian | Gió | Sa mạc |\n| Băng hà | Băng | Vùng ôn đới |\n| Sườn tích | Trọng lực | Chân núi |\n\nTại Pimpama: đất **phù sa** do nước vận chuyển.`, quiz:[{q:"Đất tàn tích hình thành như thế nào?",options:["Do gió","Tại chỗ từ phong hóa đá gốc","Do nước","Do băng hà"],ans:1,explain:"Tại chỗ từ phong hóa đá gốc bên dưới."},{q:"Tác nhân vận chuyển đất phù sa là?",options:["Gió","Băng","Nước","Trọng lực"],ans:2,explain:"Đất phù sa được nước vận chuyển và lắng đọng."}]},
      { id:"2-3", title:"Khoáng vật học đất", content:`## 2.3 Khoáng vật học đất\n\n| Khoáng vật | Trương nở | Đặc điểm |\n|------------|-----------|----------|\n| **Kaolinite** | Thấp | Ổn định, vùng nhiệt đới |\n| **Illite** | Vừa | Trung gian |\n| **Montmorillonite** | **Rất cao** | Nguy hiểm cho công trình |\n\n> ⚠️ Montmorillonite có thể trương nở thể tích đến **15 lần**, gây nứt vỡ nghiêm trọng.`, quiz:[{q:"Khoáng vật sét nào trương nở mạnh nhất?",options:["Kaolinite","Illite","Montmorillonite","Chlorite"],ans:2,explain:"Montmorillonite trương nở rất mạnh, tăng thể tích đến 15 lần."}]},
      { id:"2-4", title:"Thăm dò đất", content:`## 2.4 Thăm dò đất\n\n### Phương pháp thăm dò\n- **Nghiên cứu sơ bộ:** thu thập bản đồ địa chất\n- **Hố khoan (Boreholes):** khoan auger, washbore\n- **Mẫu U50:** đường kính 50 mm, không phá hoại\n\n### Mô tả đất trong nhật ký hố khoan\n\n| Ký hiệu | Ý nghĩa |\n|---------|---------|\n| VS | Very Soft – Rất mềm |\n| S | Soft – Mềm |\n| F | Firm – Hơi cứng |\n| St | Stiff – Cứng |\n| VST | Very Stiff – Rất cứng |`, quiz:[{q:"Mẫu U50 có đường kính bao nhiêu?",options:["25 mm","50 mm","75 mm","100 mm"],ans:1,explain:"U50 = undisturbed sample 50 mm diameter."},{q:"VS trong nhật ký hố khoan nghĩa là?",options:["Very Stiff","Very Soft","Very Sandy","Very Saturated"],ans:1,explain:"VS = Very Soft — Rất mềm."}]}
    ]
  },
  {
    id: 3, title: "Thành phần đất", icon: "⚗️", color: "#2e6da8",
    sections: [
      { id:"3-1", title:"Ba pha trong đất", content:`## 3.1 Ba pha trong đất\n\nĐất là vật liệu **đa pha** gồm:\n\n| Pha | Ký hiệu | Thể tích | Khối lượng |\n|-----|---------|---------|------------|\n| Hạt rắn | s | $V_s$ | $M_s$ |\n| Nước | w | $V_w$ | $M_w$ |\n| Khí | a | $V_a$ | $\\approx 0$ |\n| **Tổng** | | $V = V_s + V_v$ | $M = M_s + M_w$ |\n\nThể tích lỗ rỗng: $V_v = V_w + V_a$\n\nThể tích tổng: $V = V_s + V_w + V_a$`, quiz:[{q:"Đất tự nhiên gồm bao nhiêu pha?",options:["1","2","3","4"],ans:2,explain:"3 pha: hạt rắn, nước và khí."},{q:"Thể tích lỗ rỗng $V_v$ bằng?",options:["$V_s + V_w$","$V_w + V_a$","$V_s + V_a$","$V - V_s$"],ans:1,explain:"$V_v = V_w + V_a$ — tổng thể tích nước và khí."}]},
      { id:"3-2", title:"Tỷ số thể tích", content:`## 3.2 Tỷ số thể tích\n\n### Tỷ lệ rỗng (Void Ratio) — $e$\n\n$$e = \\frac{V_v}{V_s}$$\n\nThông thường: $e = 0.3 \\div 1.5$. Sét mềm: $e > 1.0$.\n\n### Mật độ tương đối — $D_r$\n\n$$D_r = \\frac{e_{max} - e}{e_{max} - e_{min}} \\times 100\\%$$\n\n| $D_r$ (%) | Trạng thái |\n|-----------|------------|\n| 0–15 | Rất rời |\n| 15–65 | Rời – Trung bình |\n| 65–100 | Chặt – Rất chặt |\n\n### Độ rỗng — $n$\n\n$$n = \\frac{V_v}{V} \\times 100\\% \\qquad n = \\frac{e}{1+e}$$\n\n### Độ bão hòa — $S$\n\n$$S = \\frac{V_w}{V_v} \\times 100\\%$$`, quiz:[{q:"Tỷ lệ rỗng $e$ bằng?",options:["$V_s/V_v$","$V_v/V_s$","$V_v/V$","$V/V_s$"],ans:1,explain:"$e = V_v/V_s$ — thể tích lỗ rỗng chia thể tích hạt rắn."},{q:"Khi $S = 100\\%$ đất ở trạng thái nào?",options:["Khô hoàn toàn","Bão hòa hoàn toàn","Bán bão hòa","Tự nhiên"],ans:1,explain:"$S=100\\%$: toàn bộ lỗ rỗng chứa đầy nước — bão hòa hoàn toàn."}]},
      { id:"3-3", title:"Tỷ số khối lượng", content:`## 3.3 Tỷ số khối lượng\n\n### Độ ẩm — $w$\n\n$$w = \\frac{M_w}{M_s} \\times 100\\%$$\n\n### Mật độ và Trọng lượng đơn vị\n\n$$\\rho = \\frac{M}{V} \\quad (\\text{g/cm}^3) \\qquad \\gamma = \\rho \\cdot g \\quad (\\text{kN/m}^3)$$\n\n| Loại đất | $\\gamma$ (kN/m³) |\n|----------|------------------|\n| Cát khô | 14–17 |\n| Cát bão hòa | 18–21 |\n| Sét mềm | 15–18 |\n| Sét cứng | 18–21 |\n\n### Trọng lượng riêng hạt — $G_s$\n\n$$G_s = \\frac{\\rho_s}{\\rho_w} \\approx 2.65 \\div 2.72$$\n\n### Công thức liên hệ hữu ích\n\n$$\\gamma_d = \\frac{\\gamma}{1+w} \\qquad S \\cdot e = G_s \\cdot w$$\n\n$$\\gamma_{sat} = \\frac{(G_s + e)\\gamma_w}{1+e} \\qquad \\gamma' = \\gamma_{sat} - \\gamma_w$$`, quiz:[{q:"$G_s$ của phần lớn đất khoáng vào khoảng?",options:["1.5–2.0","2.6–2.8","3.0–3.5","0.5–1.0"],ans:1,explain:"$G_s \\approx 2.65 \\div 2.72$ cho hầu hết đất khoáng."},{q:"Công thức mật độ khô $\\gamma_d$?",options:["$\\gamma(1+w)$","$\\gamma/(1+w)$","$\\gamma+w$","$\\gamma-w$"],ans:1,explain:"$\\gamma_d = \\gamma/(1+w)$."}]}
    ]
  },
  {
    id: 4, title: "Phân loại đất", icon: "🗂️", color: "#6b47b5",
    sections: [
      { id:"4-1", title:"Kích thước hạt và thí nghiệm rây", content:`## 4.1 Kích thước hạt và Thí nghiệm rây\n\n| Loại đất | Kích thước hạt |\n|----------|----------------|\n| Đá cuội | > 4.75 mm |\n| Cát thô | 2.0–4.75 mm |\n| Cát mịn | 0.075–0.425 mm |\n| Bột | 0.002–0.075 mm |\n| **Sét** | **< 0.002 mm** |\n\n### Thông số đường cong cấp phối\n\n$$C_u = \\frac{D_{60}}{D_{10}} \\qquad C_c = \\frac{D_{30}^2}{D_{60} \\times D_{10}}$$\n\n| Điều kiện | Phân loại |\n|-----------|-----------|\n| $C_u > 6$ và $1 \\leq C_c \\leq 3$ | Cát tốt (SW) |\n| Không đạt | Cát kém (SP) |`, quiz:[{q:"Kích thước hạt sét theo USCS?",options:["< 0.075 mm","< 0.002 mm","< 0.425 mm","< 0.06 mm"],ans:1,explain:"Sét: < 0.002 mm theo USCS."},{q:"Cát phân loại tốt (SW) cần $C_u$?",options:["$C_u < 4$","$C_u > 6$","$C_u = 1$","$C_u > 10$"],ans:1,explain:"SW: $C_u > 6$ và $1 \\leq C_c \\leq 3$."}]},
      { id:"4-2", title:"Giới hạn Atterberg", content:`## 4.2 Giới hạn Atterberg\n\n$$\\text{Rắn} \\xrightarrow{PL} \\text{Dẻo} \\xrightarrow{LL} \\text{Lỏng}$$\n\n### Chỉ số dẻo (Plasticity Index)\n\n$$PI = LL - PL$$\n\n| PI | Tính dẻo |\n|----|----------|\n| < 7 | Thấp |\n| 7–17 | Vừa |\n| > 17 | Cao |\n\n### Chỉ số lỏng (Liquidity Index)\n\n$$LI = \\frac{w - PL}{LL - PL}$$\n\n| LI | Trạng thái |\n|----|------------|\n| < 0 | Rắn |\n| 0–1 | Dẻo |\n| > 1 | Lỏng — nguy hiểm! |`, quiz:[{q:"$PI$ tính bằng?",options:["$LL + PL$","$LL - PL$","$PL - LL$","$LL \\times PL$"],ans:1,explain:"$PI = LL - PL$."},{q:"$LI > 1$ đất ở trạng thái?",options:["Rắn","Dẻo","Lỏng — nguy hiểm","Nửa cứng"],ans:2,explain:"$LI > 1$: đất lỏng, cường độ rất thấp."}]},
      { id:"4-3", title:"Hệ thống phân loại USCS", content:`## 4.3 Phân loại đất USCS\n\n### Đất thô\n- **GW/GP:** Sỏi tốt/kém | **SW/SP:** Cát tốt/kém\n- **GM/SM:** Sỏi/Cát pha bột | **GC/SC:** Sỏi/Cát pha sét\n\n### Đất mịn\n- **ML/MH:** Bột dẻo thấp/cao\n- **CL:** Sét dẻo thấp | **CH:** Sét dẻo cao\n\n### Biểu đồ dẻo — Đường A\n\n$$PI = 0.73(LL - 20)$$\n\n- **Trên** đường A: Sét (C)\n- **Dưới** đường A: Bột (M)\n\n> Sét phù sa Pimpama: $LL \\approx 65\\%$, $PI \\approx 35\\%$ → **CH**`, quiz:[{q:"Đường A trong biểu đồ dẻo?",options:["$PI = 0.73(LL-20)$","$PI = 0.9(LL-8)$","$PI = LL-20$","$PI = 0.5LL$"],ans:0,explain:"Đường A: $PI = 0.73(LL-20)$."},{q:"CH là gì?",options:["Sét dẻo thấp","Sét dẻo cao","Bột dẻo thấp","Cát pha sét"],ans:1,explain:"CH = Clay High plasticity — Sét dẻo cao."}]}
    ]
  },
  {
    id: 5, title: "Đầm chặt đất", icon: "🔨", color: "#c0392b",
    sections: [
      { id:"5-1", title:"Quá trình đầm chặt và Proctor", content:`## 5.1 Đầm chặt và Thí nghiệm Proctor\n\n> ⚠️ Phân biệt: **Đầm chặt** loại bỏ khí; **Cố kết** loại bỏ nước.\n\n### Mục đích\n- Tăng khả năng chịu tải, giảm độ lún\n- Giảm hệ số thấm, tăng ổn định mái dốc\n\n### Thí nghiệm Proctor Tiêu chuẩn\n- Khuôn: **944 cm³** | Búa: **2.5 kg**, rơi **305 mm**\n- 3 lớp × 25 chày/lớp\n\n**Mật độ khô:**\n$$\\rho_d = \\frac{\\rho}{1+w}$$\n\n**Đường ZAV ($S = 100\\%$):**\n$$\\rho_{d,ZAV} = \\frac{G_s \\cdot \\rho_w}{1 + G_s \\cdot w}$$`, quiz:[{q:"Đầm chặt loại bỏ thành phần nào?",options:["Nước","Khí","Cả hai","Hạt mịn"],ans:1,explain:"Đầm chặt loại bỏ khí, cố kết loại bỏ nước."},{q:"Búa Proctor tiêu chuẩn nặng bao nhiêu?",options:["1.0 kg","2.5 kg","4.5 kg","10 kg"],ans:1,explain:"Proctor chuẩn: 2.5 kg, rơi 305 mm."}]},
      { id:"5-2", title:"Đầm chặt hiện trường", content:`## 5.2 Đầm chặt ngoài Hiện trường\n\n| Thiết bị | Thích hợp |\n|----------|-----------|\n| Lu bánh lốp | Cát, sỏi |\n| Lu chân cừu | Đất dính |\n| Lu rung | Cát, sỏi |\n| Đầm cóc | Khu chật hẹp |\n\n### Kiểm tra chất lượng\n\n$$RC = \\frac{\\rho_{d,field}}{\\rho_{d,max}} \\times 100\\% \\geq 95\\%$$\n\n### Dự án Pimpama\nĐất phù sa: $w_{opt} \\approx 20\\div25\\%$, $\\rho_{d,max} \\approx 1.65$ g/cm³`, quiz:[{q:"Độ chặt yêu cầu $RC$ tối thiểu?",options:["85%","90%","95%","100%"],ans:2,explain:"RC ≥ 95% theo tiêu chuẩn thi công."},{q:"Lu chân cừu dùng cho đất nào?",options:["Cát sạch","Sỏi thô","Đất dính (sét)","Đá dăm"],ans:2,explain:"Lu chân cừu tốt cho đất dính."}]}
    ]
  },
  {
    id: 6, title: "Ứng suất trong đất", icon: "⚖️", color: "#d35400",
    sections: [
      { id:"6-1", title:"Ứng suất tổng và hữu hiệu", content:`## 6.1 Ứng suất Tổng và Hữu hiệu\n\n### Ứng suất tổng đứng\n$$\\sigma_v = \\sum \\gamma_i \\cdot h_i$$\n\n### Nguyên lý Terzaghi (1943)\n\n$$\\boxed{\\sigma' = \\sigma - u}$$\n\n| Ký hiệu | Ý nghĩa |\n|---------|----------|\n| $\\sigma'$ | Ứng suất hữu hiệu — **gây biến dạng** |\n| $\\sigma$ | Ứng suất tổng |\n| $u$ | Áp lực nước lỗ rỗng |\n\n$$u = \\gamma_w \\cdot h_w \\qquad \\sigma'_h = K_0 \\cdot \\sigma'_v$$\n\nVới NC soil: $K_0 = 1 - \\sin\\phi'$`, quiz:[{q:"Nguyên lý Terzaghi: $\\sigma' =$?",options:["$\\sigma + u$","$\\sigma - u$","$u - \\sigma$","$\\sigma \\times u$"],ans:1,explain:"$\\sigma' = \\sigma - u$."},{q:"Thành phần nào gây biến dạng đất?",options:["Ứng suất tổng $\\sigma$","Áp lực nước $u$","Ứng suất hữu hiệu $\\sigma'$","Tất cả như nhau"],ans:2,explain:"Chỉ $\\sigma'$ tác dụng lên khung hạt mới gây biến dạng."}]},
      { id:"6-2", title:"Thấm hướng lên và đất chảy", content:`## 6.2 Thấm hướng lên và Điều kiện đất chảy\n\n### Gradient thủy lực\n$$i = \\frac{\\Delta h}{L}$$\n\n### Thấm hướng lên\n$$\\sigma' = (\\gamma' - i \\cdot \\gamma_w) \\cdot z$$\n\n### Điều kiện đất chảy (Quick Condition)\n\nKhi $\\sigma' = 0$:\n\n$$i_{cr} = \\frac{\\gamma'}{\\gamma_w} = \\frac{G_s - 1}{1+e} \\approx 0.9 \\div 1.1$$\n\n> ⚠️ Khi $i > i_{cr}$: **đất chảy (quicksand)** — mất hoàn toàn cường độ.`, quiz:[{q:"Gradient tới hạn $i_{cr}$ bằng?",options:["$\\gamma'/\\gamma_w$","$\\gamma_w/\\gamma'$","$\\gamma/\\gamma_w$","$1.5$"],ans:0,explain:"$i_{cr} = \\gamma'/\\gamma_w \\approx 0.9 \\div 1.1$."},{q:"Đất chảy xảy ra khi?",options:["$i < i_{cr}$","$i = 0$","$i > i_{cr}$","$i = i_{cr}/2$"],ans:2,explain:"$i > i_{cr}$: ứng suất hữu hiệu = 0, đất mất cường độ."}]}
    ]
  },
  {
    id: 7, title: "Dòng thấm trong đất", icon: "💧", color: "#1a6fa8",
    sections: [
      { id:"7-1", title:"Định luật Darcy và hệ số thấm", content:`## 7.1 Định luật Darcy và Hệ số thấm\n\n| Loại đất | $k$ (m/s) |\n|----------|-----------|\n| Sỏi | $10^{-1}$ đến $1$ |\n| Cát thô | $10^{-4}$ đến $10^{-2}$ |\n| Cát mịn | $10^{-6}$ đến $10^{-4}$ |\n| Bột | $10^{-9}$ đến $10^{-5}$ |\n| Sét | $10^{-11}$ đến $10^{-8}$ |\n\n### Định luật Darcy\n\n$$v = k \\cdot i \\qquad q = k \\cdot i \\cdot A$$\n\n- $v$ = vận tốc thấm | $i = \\Delta h/L$ | $q$ = lưu lượng\n- Áp dụng cho **chảy tầng** ($Re < 10$)`, quiz:[{q:"Định luật Darcy: $v =$?",options:["$v = k/i$","$v = k \\cdot i$","$v = i/k$","$v = k + i$"],ans:1,explain:"$v = k \\cdot i$."},{q:"Đất sét có $k$ vào khoảng?",options:["$10^{-1}$ m/s","$10^{-4}$ m/s","$10^{-9}$ m/s","$1$ m/s"],ans:2,explain:"Sét: $k \\approx 10^{-11}$ đến $10^{-8}$ m/s — thấm rất kém."}]},
      { id:"7-2", title:"Thí nghiệm thấm và lưới thấm", content:`## 7.2 Thí nghiệm Thấm và Lưới thấm\n\n### Constant Head (đất thô)\n$$k = \\frac{q \\cdot L}{A \\cdot \\Delta h}$$\n\n### Falling Head (đất mịn)\n$$k = \\frac{a \\cdot L}{A(t_2-t_1)} \\cdot \\ln\\frac{h_1}{h_2}$$\n\n### Thấm trong đất phân lớp\n$$k_H = \\frac{\\sum k_i h_i}{\\sum h_i} \\geq k_V = \\frac{\\sum h_i}{\\sum h_i/k_i}$$\n\n### Lưu lượng qua lưới thấm\n$$q = k \\cdot H \\cdot \\frac{N_f}{N_d}$$\n\n$N_f$ = số ô dòng, $N_d$ = số ô đẳng thế`, quiz:[{q:"Falling Head dùng cho loại đất nào?",options:["Cát sạch","Sỏi thô","Đất mịn (sét, bột)","Đất hữu cơ"],ans:2,explain:"Falling Head dùng cho đất mịn, thấm chậm."},{q:"$k_H$ so với $k_V$?",options:["$k_H < k_V$","$k_H = k_V$","$k_H \\geq k_V$","Ngẫu nhiên"],ans:2,explain:"$k_H \\geq k_V$ — thấm ngang luôn ≥ thấm đứng."}]}
    ]
  },
  {
    id: 8, title: "Vòng tròn Mohr và ứng suất", icon: "⭕", color: "#7d3c98",
    sections: [
      { id:"8-1", title:"Vòng tròn Mohr", content:`## 8.1 Vòng tròn Mohr\n\n### Ứng suất trên mặt phẳng nghiêng góc $\\theta$\n\n$$\\sigma_\\theta = \\frac{\\sigma_1+\\sigma_3}{2} + \\frac{\\sigma_1-\\sigma_3}{2}\\cos 2\\theta$$\n\n$$\\tau_\\theta = \\frac{\\sigma_1-\\sigma_3}{2}\\sin 2\\theta$$\n\n### Thông số vòng tròn\n\n- **Tâm:** $O = \\left(\\dfrac{\\sigma_1+\\sigma_3}{2},\\ 0\\right)$\n- **Bán kính:** $R = \\dfrac{\\sigma_1-\\sigma_3}{2} = \\tau_{max}$\n\nỨng suất cắt lớn nhất tại $\\theta = 45°$.`, quiz:[{q:"Bán kính vòng tròn Mohr bằng?",options:["$(\\sigma_1+\\sigma_3)/2$","$(\\sigma_1-\\sigma_3)/2$","$\\sigma_1 \\cdot \\sigma_3$","$\\sigma_1/\\sigma_3$"],ans:1,explain:"$R = (\\sigma_1-\\sigma_3)/2 = \\tau_{max}$."},{q:"$\\tau_{max}$ xảy ra trên mặt phẳng nghiêng bao nhiêu độ?",options:["0°","30°","45°","90°"],ans:2,explain:"$\\tau_{max}$ tại $\\theta = 45°$."}]},
      { id:"8-2", title:"Phương pháp Cực (Pole)", content:`## 8.2 Phương pháp Cực (Pole Method)\n\n### Các bước thực hiện\n1. Vẽ vòng tròn Mohr với $A(\\sigma_3, 0)$ và $B(\\sigma_1, 0)$\n2. Điểm cực $P$: vẽ đường **ngang** từ $A$ → giao vòng tròn\n3. Từ $P$, vẽ đường **song song mặt phẳng** cần xét\n4. Giao điểm → $(\\sigma_\\theta, \\tau_\\theta)$\n\n### Ứng dụng\n- Phân tích ổn định mái dốc\n- Tính áp lực đất lên tường chắn\n- Thiết kế nền móng`, quiz:[{q:"Vòng tròn Mohr dùng để làm gì?",options:["Phân tích thấm","Xác định ứng suất mặt phẳng bất kỳ","Tính lún","Đo thấm"],ans:1,explain:"Biểu diễn trạng thái ứng suất tại mọi mặt phẳng."}]}
    ]
  },
  {
    id: 9, title: "Biến dạng đất", icon: "📐", color: "#1e8449",
    sections: [
      { id:"9-1", title:"Thí nghiệm cường độ đất", content:`## 9.1 Thí nghiệm Cường độ Đất\n\n### Thí nghiệm nén không hạn chế (UCT)\n$$q_u = \\frac{P}{A} \\qquad c_u = \\frac{q_u}{2}$$\n\n### Thí nghiệm Ba trục (Triaxial Test)\n\n| Ký hiệu | Tên | Điều kiện |\n|---------|-----|------------|\n| **UU** | Không cố kết – Không thoát nước | Ứng suất tổng |\n| **CU** | Cố kết – Không thoát nước | $\\sigma' + u$ |\n| **CD** | Cố kết – Thoát nước | Tham số hữu hiệu |\n\n### Hệ số Skempton\n$$\\Delta u = B[\\Delta\\sigma_3 + A(\\Delta\\sigma_1 - \\Delta\\sigma_3)]$$\n- Bão hòa: $B = 1$ | NC clay: $A \\approx 0.5 \\div 1.0$`, quiz:[{q:"UCT cho thông số nào?",options:["$\\phi'$","$c_u$","Hệ số thấm","Giới hạn chảy"],ans:1,explain:"$c_u = q_u/2$ từ thí nghiệm UCT."},{q:"CD cho tham số nào chính xác nhất?",options:["$c', \\phi'$ hữu hiệu","Chỉ số dẻo","Hệ số thấm","Mật độ hạt"],ans:0,explain:"CD (cố kết – thoát nước) cho $c'$ và $\\phi'$ chính xác nhất."}]}
    ]
  },
  {
    id: 10, title: "Cố kết đất mềm", icon: "⏱️", color: "#148f77",
    sections: [
      { id:"10-1", title:"Quá trình cố kết và các loại lún", content:`## 10.1 Quá trình Cố kết\n\n**Cố kết:** Đất mịn nén chặt dần do **nước lỗ rỗng thoát ra chậm** dưới tải trọng.\n\n### Các loại lún\n$$S_{total} = S_i + S_c + S_s$$\n\n| Loại | Ký hiệu | Nguyên nhân |\n|------|---------|-------------|\n| Tức thời | $S_i$ | Biến dạng không thoát nước |\n| Sơ cấp | $S_c$ | Thoát nước lỗ rỗng |\n| Từ biến | $S_s$ | Biến dạng từ biến |`, quiz:[{q:"Cố kết là quá trình gì?",options:["Đầm cơ học","Thoát nước chậm → lún theo thời gian","Đóng băng","Tăng cường độ tức thì"],ans:1,explain:"Nước lỗ rỗng thoát chậm → đất lún dần theo thời gian."}]},
      { id:"10-2", title:"Tính lún cố kết", content:`## 10.2 Tính Lún Cố kết\n\n### Thông số từ Oedometer\n- $C_c$ = Chỉ số nén | $C_s \\approx C_c/5 \\div C_c/10$\n\n### Lún — NC soil ($OCR = 1$)\n$$S_c = \\frac{C_c}{1+e_0} \\cdot H_0 \\cdot \\log\\frac{\\sigma'_0 + \\Delta\\sigma'}{\\sigma'_0}$$\n\n### Lún — OC soil ($\\sigma'_0 + \\Delta\\sigma' \\leq \\sigma'_c$)\n$$S_c = \\frac{C_s}{1+e_0} \\cdot H_0 \\cdot \\log\\frac{\\sigma'_0 + \\Delta\\sigma'}{\\sigma'_0}$$`, quiz:[{q:"$C_c$ xác định từ đường cong nào?",options:["Cấp phối hạt","$e - \\log\\sigma'$","Proctor","Thấm"],ans:1,explain:"$C_c$ = độ dốc đường cố kết trên $e - \\log\\sigma'$."}]},
      { id:"10-3", title:"Lý thuyết Terzaghi và OCR", content:`## 10.3 Lý thuyết Cố kết Terzaghi và OCR\n\n### Phương trình cố kết 1D\n$$c_v \\frac{\\partial^2 u}{\\partial z^2} = \\frac{\\partial u}{\\partial t} \\qquad c_v = \\frac{k}{m_v \\cdot \\gamma_w}$$\n\n### Nhân tố thời gian\n$$T_v = \\frac{c_v \\cdot t}{H_{dr}^2}$$\n\n| $T_v$ | $U$ (%) |\n|-------|---------|\n| 0.008 | 10 |\n| 0.197 | 50 |\n| 0.405 | 70 |\n| 0.848 | 90 |\n\n### Tỷ số quá cố kết\n$$OCR = \\frac{\\sigma'_c}{\\sigma'_{v0}}$$\n\n| OCR | Trạng thái |\n|-----|------------|\n| $= 1$ | NC — bình thường |\n| $> 1$ | OC — quá cố kết |`, quiz:[{q:"Thoát nước 2 chiều: $H_{dr}$ bằng?",options:["$H$","$H/2$","$2H$","$H/4$"],ans:1,explain:"Hai chiều: $H_{dr} = H/2$."},{q:"NC soil có $OCR$?",options:["$< 1$","$= 1$","$> 1$","$= 0$"],ans:1,explain:"$OCR = 1$: ứng suất hiện tại = ứng suất cố kết lớn nhất."},{q:"Tăng $k$ ảnh hưởng thế nào đến $c_v$?",options:["Giảm $c_v$","Tăng $c_v$","Không đổi","Phụ thuộc loại đất"],ans:1,explain:"$c_v = k/(m_v \\cdot \\gamma_w)$ — tăng $k$ → tăng $c_v$ → cố kết nhanh hơn."}]}
    ]
  },
  {
    id: 11, title: "Sức chống cắt và ổn định mái dốc", icon: "⛰️", color: "#922b21",
    sections: [
      { id:"11-1", title:"Tiêu chuẩn Mohr-Coulomb", content:`## 11.1 Tiêu chuẩn Mohr-Coulomb\n\n$$\\tau_f = c' + \\sigma'_n \\tan\\phi'$$\n\n| Tham số | Ý nghĩa | Điển hình |\n|---------|---------|----------|\n| $c'$ | Lực dính hữu hiệu | 0–50 kPa |\n| $\\phi'$ | Góc ma sát trong | 20°–40° |\n\n### Thí nghiệm hộp cắt\n$$\\tau_f = \\frac{F}{A} \\qquad \\sigma'_n = \\frac{N}{A}$$\n\nVẽ 3 điểm $(\\sigma'_n, \\tau_f)$ → đường Mohr-Coulomb → $c'$, $\\phi'$.`, quiz:[{q:"Mohr-Coulomb: $\\tau_f =$?",options:["$c' + \\sigma'\\tan\\phi'$","$c' - \\sigma'\\tan\\phi'$","$\\sigma'/\\tan\\phi'$","$c' \\cdot \\sigma'$"],ans:0,explain:"$\\tau_f = c' + \\sigma'\\tan\\phi'$."}]},
      { id:"11-2", title:"Phân tích ổn định mái dốc", content:`## 11.2 Phân tích Ổn định Mái dốc\n\n### Mái dốc vô hạn (Infinite Slope)\n\n**Thoát nước:**\n$$FS = \\frac{\\tan\\phi'}{\\tan\\beta}$$\n\n**Mực nước ngầm ở bề mặt:**\n$$FS = \\frac{\\gamma'}{\\gamma_{sat}} \\cdot \\frac{\\tan\\phi'}{\\tan\\beta}$$\n\n### Bishop Đơn giản (mặt trượt tròn)\n$$FS = \\frac{\\sum \\left[\\dfrac{c'b + (W-ub)\\tan\\phi'}{m_{\\alpha}}\\right]}{\\sum W\\sin\\alpha}$$\n\n$$m_{\\alpha} = \\cos\\alpha + \\frac{\\tan\\phi'\\sin\\alpha}{FS}$$\n\n### Dự án Pimpama\n$\\beta = 18°$, $c_u = 10$ kPa, $\\phi_u = 0°$ → $FS \\approx 1.1 \\div 1.3$ ⚠️ Không đạt!`, quiz:[{q:"FS tối thiểu cho mái dốc?",options:["$\\geq 1.0$","$\\geq 1.5$","$\\geq 3.0$","$\\geq 0.5$"],ans:1,explain:"FS ≥ 1.5 yêu cầu tối thiểu."},{q:"Mái dốc vô hạn không thấm: FS?",options:["$\\tan\\phi'/\\tan\\beta$","$\\tan\\beta/\\tan\\phi'$","$c'/(\\gamma H)$","$\\gamma'/\\gamma_{sat}$"],ans:0,explain:"$FS = \\tan\\phi'/\\tan\\beta$."},{q:"Bishop đơn giản giả định lực giữa các mảnh?",options:["Bằng 0","Nằm ngang","Vuông góc mặt trượt","Song song mặt dốc"],ans:1,explain:"Bishop đơn giản: lực giữa mảnh nằm ngang."}]}
    ]
  }
];

export const getAllSections = () =>
  CHAPTERS.flatMap(ch =>
    ch.sections.map(s => ({ ...s, chapterId: ch.id, chapterTitle: ch.title, chapterColor: ch.color, chapterIcon: ch.icon }))
  );
